-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH FROM MEMBER_PROFILE
WHERE DATE_FORMAT(DATE_OF_BIRTH, '%m') = '03' 
AND GENDER = 'W'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;


-- memo
-- DATE_FORMAT 대신 MONTH를 사용하는 방법도 있다.